language: node_js
sudo: false
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    - ubuntu-toolchain-r-test
    packages:
    - google-chrome-stable
    - g++-4.8
node_js:
- '4.2'
- '5.1'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- npm i -g bower@1.7.1 gulp@3.9.0 firebase-tools@2.2.0
- bower i
script:
- "./travis-runner.sh"
env:
  global:
  - CXX='g++-4.8'
  - secure: ltlbqDuxnww0VDw7t2S2m7k+vrd95hDBrfHcwP47WkTPA0h/7VcmsXWkOdDi9vpsR4nzFSvJgSjDZDR/cNruroFaLaZ9x3Dzddc+hl5lhQdPx48R8bHLdtH1Zn5HtXDnDIr/zQowvnkdy/2yErMGDGZYM3FLULw3WbJo1j6NqHQ6JU5PbOv29JPwc/P0Bi5DgE3FhHJvWh6W8Yuh1S3iG3J06VZWorL4hGq+Lgp/SeJw6ZrrVPOHARGb+cIrQ0H/ka96M1+13a6T+uLTBPIXU7TLXR2TMmeoCPWzz033StxwzW8uU7KB+WLiwuKBZNe5t10u+bnuRbf4hbwe+PQMgpW4uGSVZjY49g2mlMVXKEXIX506dfFCY44i0U6CInCpGWg/iGkOuvmcBI8mkDy+ZNwQB3KvrnofNHrKOwcVg9GaiYx23P9EgR9YDCYNnhnaar4PUgx5Yrv3kfMi8Xvfb3+5KsACK+0xAZYKfpFeUF4bO8aNPqfcqdbNViSSZ1dWRhH6jniaRNnCeqoOBpnA8ZLuawEv5SHjjez0RTGt8cTwp8vL9xgiA4XJE4yLGsehR5LqhLtmA8zAjISnallx3ISfRvc1x25N0R/KSBLnZeQBXnBTuzLsfRsiMMQtdPYeTAvigAntsIdCGLLlh0b2rGiHYEdGs2TiLRnG5ZO7Wdk=
